# Generated by Django 4.2.11 on 2024-04-19 19:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymslotbooking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='full_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='slot',
        ),
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(default=datetime.date(2024, 4, 19)),
        ),
        migrations.AddField(
            model_name='booking',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 4, 19, 19, 12, 5, 278932)),
        ),
    ]
