# Generated by Django 4.2.11 on 2024-04-19 19:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymslotbooking', '0002_rename_full_name_booking_name_remove_booking_slot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 4, 19, 19, 19, 32, 884119)),
        ),
    ]
